language: python
python:
- '3.4'
install:
  - pip install -r requirements.txt
  - pip install coveralls
notifications:
  email:
    recipients:
      - jgomez@getty.edu
script:
  coverage run --source=pyalma setup.py test
after_success:
  coveralls

